### ISSUE TITLE
for identity block which input to bypass

### ISSUE THREAD

**Issue by Kraut-Inferences** [DowellChan/ResNetRegression#1]
am i suppose to take the original input pass the identity block or am i suppose to take the dense blocks add+outer dense output to the identity block?

**Comment by DowellChan** [comment]
Hi, Kraut, 

It's kind of confusing that we write input and output in the clarification figures of identity block and dense block. Actually it's not the input and output of the neural network. The input of a identity block is just the output of its last identity block or dense block. Similarly, the output of a identity block is just the input of the next identity block or dense block. I hope this could make a clarification for you. 

Regards, 
Dongwei

**Comment by Kraut-Inferences** [comment]
it does thank you.
