### ISSUE TITLE
老师您好，请问可以提供一下您程序里面使用的数据吗

### ISSUE THREAD

**Issue by niecj09** [DowellChan/ResNetRegression#2]
path = "~/pub/dwchen/testData/min400800.csv"

**Comment by DowellChan** [comment]
Please give me your email address.

**Comment by niecj09** [comment]
my email ***@***.*** you very much~-------- 原始邮件 --------发件人： dwchen ***@***.***>日期： 2021年10月16日周六 22:34收件人： DowellChan/ResNetRegression ***@***.***>抄送： niecj09 ***@***.***>, Author ***@***.***>主    题： Re: [DowellChan/ResNetRegression] 老师您好，请问可以提供一下您程序里面使用的数据吗 (#2)
Please give me your email address.

**Comment by DowellChan** [comment]
you need to download this data from google drive. 

(1). min400800.csv https://drive.google.com/file/d/1chpK4PKv2P9umY2t2pkwsKKxFhGImZxg/view?usp=sharing

(2). min4008001200.csv https://drive.google.com/file/d/1D3P9ZxMsiZVz6Xpq5G9s5SUGQZ_Ln0ak/view?usp=sharing

Note that they are simulated datasets, so actually you could build your own data.
